# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  my-executer:
    docker:
      - image: cimg/ruby:2.6.5-node
      - image: cimg/python:3.10.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    executor: my-executer
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  check-env:
    executor: my-executer
    steps:
      - checkout
      - run:
          name: "check Ruby version"
          command: ruby --version
      - run:
          name: "check Node.js version"
          command: node --version
      - run:
          name: "check Python version"
          command: python3 --version
  cfn-lint:
    executor: my-executor
    steps:
      - checkout
      - run: sudo pip install cfn-lint
      - run: cd cloud_formation
      - run: cfn-lint 01_vpc.yml
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  my-workflow:
    jobs:
      - say-hello
      - check-env
      - cfn-lint:
          requires:
            - check-env
