AWSTemplateFormatVersion: 2010-09-09

Description: "CloudFormation Templete for creating S3"

Parameters:
  PREFIX:
    Type: String
    Default: practice
  BucketName:
    Type: String
    Default: s3-20220210

Resources:
  # S3 Bucket
  myS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub ${BucketName}

  # Bucket Policy
  s3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref myS3Bucket
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal: "*"
          Action:
            - s3:GetObject
            - s3:GetObjectVersion
          Resource: !Sub arn:aws:s3:::${PREFIX}-${BucketName}/*
