13.113.166.148:
  :roles:
    - base
    - app
    - web
  :ssh_opts:
    :user: ec2-user
    :paranoid: false
54.178.24.185:
  :roles:
    - base
    - app
    - web
  :ssh_opts:
    :user: ec2-user
    :paranoid: false
