require 'rake'
require 'rspec/core/rake_task'
require 'yaml'

properties = YAML.load_file("hosts.yml")

task desc "Run serverspec to all hosts"
task :spec => 'spec:all'

namespace :spec do
  task :all => properties.keys.map {|key| 'spec:' + key }
  properties.each_key do |key|
    desc "Run serverspec to #{key}"
    RSpec::Core::RakeTask.new(key.to_sym) do |t|
      t.fail_on_error = false
      ENV['TARGET_HOST'] = key
      t.pattern = 'spec/{' + properties[key][:roles].join(',') + '}/*_spec.rb'
    end
  end
end